### PR TITLE
fixed afterPaste to combine new and old values

### LINKED ISSUE #552: pasting a value into a list field deletes any existing values
If you try to paste an additional value into a list field, you replace all existing values instead of adding an additional value.

image
<kbd>ctrl</kbd>+<kbd>v</kbd>  ->

image

### PR DESCRIPTION
**Pull request by BinaryWizard904**
Fixes #552 
When pasting values into a populated array field, the new values (whether one or many) will now be concatenated onto the old values.

### CODE REVIEW

File: src/components/tag-input.js [hunk 1]
```diff
@@ -38,7 +38,16 @@ export default class TagInput extends LitElement {
   afterPaste(e) {
     const clipboardData = e.clipboardData || window.clipboardData;
     const pastedData = clipboardData.getData('Text');
-    this.value = pastedData ? pastedData.split(',').filter((v) => v.trim() !== '') : '';
+    const pastedArray = pastedData ? pastedData.split(',').filter((v) => v.trim() !== '') : '';
+    
+    if(pastedArray) {
```
Comment (mrin9) [inline src/components/tag-input.js:43]: seems like `if ... else` is not as per the style guide. but otherwise fine (can be fixed at our end)

**Review by mrin9 — APPROVED** [review]

File: src/components/tag-input.js (hunk 1 above)
Comment (mrin9) [reply src/components/tag-input.js:43]: will fix at our end

**Comment by mrin9** [comment]
Thanks for the PR !!!
